In [1]:
# ref:
# https://onlinecourses.science.psu.edu/stat501/node/382/

import numpy as np
from numpy.linalg import inv
    
x0 = [4.0,4.5,5.0,5.5,6.0,6.5,7.0]
x = np.array([np.repeat(1, len(x0)), x0])
print (x)
print(x.T)
xx = np.matmul(x,x.T)
print(xx)
xx_i = inv(xx)
print(xx_i)

y = np.array([33,42,45,51,53,61,62])
print(y)
y_r = y.reshape((len(y),-1))
print(y_r)
xy = np.matmul(x, y_r)
print(xy)

ab = np.matmul(xx_i,xy)
print(ab)

[[1.  1.  1.  1.  1.  1.  1. ]
 [4.  4.5 5.  5.5 6.  6.5 7. ]]
[[1.  4. ]
 [1.  4.5]
 [1.  5. ]
 [1.  5.5]
 [1.  6. ]
 [1.  6.5]
 [1.  7. ]]
[[  7.    38.5 ]
 [ 38.5  218.75]]
[[ 4.46428571 -0.78571429]
 [-0.78571429  0.14285714]]
[33 42 45 51 53 61 62]
[[33]
 [42]
 [45]
 [51]
 [53]
 [61]
 [62]]
[[ 347.]
 [1975.]]
[[-2.67857143]
 [ 9.5       ]]
